timezone: America/Chicago
highlighter: rouge
markdown: kramdown
permalink: /post/:title

exclude: [README.md]

paginate: 5
paginate_path: '/blog/:num'

excerpt_separator: "\n\n\n"

name: KenBeck
domain: KenBeckTN.com
url: http://biostat.mc.vanderbilt.edu/ColeBeck
description: Articles by Ken Beck
copyright: 2015
author:
    name: Cole Beck
